### ISSUE TITLE
Does not work with current Dotnet core

### ISSUE THREAD

**Issue by RobThree** [unseen1980/.netCoreAngular2#1]
The (current) version your [README refers to](https://dotnet.github.io/getting-started/) (e.g. [this one](https://dotnetcli.blob.core.windows.net/dotnet/beta/Installers/1.0.0.001598/dotnet-win-x64.1.0.0.001598.exe)) does not work as documented:

> Install dependencies
> 
> `dnu restore`
> 
> Build the project:
> 
> `dnu build`
> 
> Launch app
> 
> `dnx web`

`dnu` is now `dotnet` and `dnx` is now `dotnet run`. Also; `dotnet build` fails:

> `Compiling .netCoreAngular2-master for DNXCore,Version=v5.0
> D:\Test\netCoreAngular2-master\.netCoreAngular2-master\project.json(13,29): error NU1002: The dependency Microsoft.CodeAnalysis.Common 1.1.0-rc1-20151109-01 does not support framework DNXCore,Version=v5.0.`
> 
> `D:\Test\netCoreAngular2-master\.netCoreAngular2-master\project.json(14,40): error NU1002: The dependency Microsoft.CodeAnalysis.Common 1.1.0-rc1-20151109-01 does not support framework DNXCore,Version=v5.0.`
> 
> `D:\Test\netCoreAngular2-master\.netCoreAngular2-master\project.json(13,29): error NU1002: The dependency Microsoft.CodeAnalysis.CSharp 1.1.0-rc1-20151109-01 does not support framework DNXCore,Version=v5.0.`
> 
> `D:\Test\netCoreAngular2-master\.netCoreAngular2-master\project.json(14,40): error NU1002: The dependency Microsoft.CodeAnalysis.CSharp 1.1.0-rc1-20151109-01 does not support framework DNXCore,Version=v5.0.`

**Comment by unseen1980** [comment]
Thank you Rob, it seems I have an older version installed. Checking it now.

**Comment by unseen1980** [comment]
Rob, there are many issues with the current .Net Core version and we are expecting a new release soon. The Omnisharp cli still has things that don't work (https://github.com/OmniSharp/generator-aspnet#generator-aspnet) 

So for the moment I suggest to use the dnu and dnx commands.

Scott Hanselman has a nice post here:
http://www.hanselman.com/blog/AnUpdateOnASPNETCore10RC2.aspx

I will update the repo once things got stable

Thanks for jumping in.

**Comment by unseen1980** [comment]
Updated to the latest version of .net core. You can now use the dotnet command.
Thanks
